global: &global
  adapter: postgresql
  min_messages: warning
  encoding: unicode
  host: localhost

development: 
  database: property_portal_dev
  <<: *global
  
test: &test
  database: property_portal_test
  <<: *global

cucumber:
  <<: *test